#include <pebble.h>

// definition of one item
uint32_t  we_data[] = {
   RESOURCE_ID_IMAGE_SLEEP,  //0
   RESOURCE_ID_IMAGE_SLEEP,  //1
   RESOURCE_ID_IMAGE_SLEEP,  //2
   RESOURCE_ID_IMAGE_SLEEP,  //3
   RESOURCE_ID_IMAGE_SLEEP,  //4
   RESOURCE_ID_IMAGE_SLEEP,  //5
   RESOURCE_ID_IMAGE_SLEEP,  //6
   RESOURCE_ID_IMAGE_SLEEP,  //7
   RESOURCE_ID_IMAGE_SLEEP,  //8
   RESOURCE_ID_IMAGE_WAKEUP,  //9
   RESOURCE_ID_IMAGE_COFFEE,  //10
   RESOURCE_ID_IMAGE_HOME,  //11
   RESOURCE_ID_IMAGE_LUNCH,  //12
   RESOURCE_ID_IMAGE_GAS,  //13
   RESOURCE_ID_IMAGE_SHOPPING,  //14
   RESOURCE_ID_IMAGE_COFFEE,  //15
   RESOURCE_ID_IMAGE_SHOPPING,  //16
   RESOURCE_ID_IMAGE_SHOPPING,  //17
   RESOURCE_ID_IMAGE_SHOPPING,  //18
   RESOURCE_ID_IMAGE_LUNCH,  //19
   RESOURCE_ID_IMAGE_LUNCH,  //20
   RESOURCE_ID_IMAGE_GLASS,  //21
   RESOURCE_ID_IMAGE_MUSIC,  //22
   RESOURCE_ID_IMAGE_GLASS  //23
};
uint32_t  data[] = {
   RESOURCE_ID_IMAGE_SLEEP,  //0
   RESOURCE_ID_IMAGE_SLEEP,  //1
   RESOURCE_ID_IMAGE_SLEEP,  //2
   RESOURCE_ID_IMAGE_SLEEP,  //3
   RESOURCE_ID_IMAGE_SLEEP,  //4
   RESOURCE_ID_IMAGE_SLEEP,  //5
   RESOURCE_ID_IMAGE_WAKEUP,  //6
   RESOURCE_ID_IMAGE_HOME,  //7
   RESOURCE_ID_IMAGE_CAR,  //8
   RESOURCE_ID_IMAGE_COFFEE,  //9
   RESOURCE_ID_IMAGE_WORK2,  //10
   RESOURCE_ID_IMAGE_WORK,  //11
   RESOURCE_ID_IMAGE_LUNCH,  //12
   RESOURCE_ID_IMAGE_LAB,  //13
   RESOURCE_ID_IMAGE_MUSIC,  //14
   RESOURCE_ID_IMAGE_COFFEE,  //15
   RESOURCE_ID_IMAGE_MUSIC,  //16
   RESOURCE_ID_IMAGE_HOME,  //17
   RESOURCE_ID_IMAGE_LUNCH,  //18
   RESOURCE_ID_IMAGE_LAPTOP,  //19
   RESOURCE_ID_IMAGE_LAPTOP,  //20
   RESOURCE_ID_IMAGE_GLASS,  //21
   RESOURCE_ID_IMAGE_SLEEP,  //22
   RESOURCE_ID_IMAGE_SLEEP  //23
};